// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvp4CGmegb2Vrm-gqUc9pGZPgZjh_DfmU',
    appId: '1:3436283578:web:892376ac0c48c37ef7e483',
    messagingSenderId: '3436283578',
    projectId: 'translation-app-a73ec',
    authDomain: 'translation-app-a73ec.firebaseapp.com',
    storageBucket: 'translation-app-a73ec.firebasestorage.app',
    measurementId: 'G-3FB5RDP1KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYMDBYgBmBNorImIBs0vxiD06B6qTzjyk',
    appId: '1:3436283578:android:030d07128cc53ac4f7e483',
    messagingSenderId: '3436283578',
    projectId: 'translation-app-a73ec',
    storageBucket: 'translation-app-a73ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcerile7xub_jHCLh70-WN__urs1ONM94',
    appId: '1:3436283578:ios:59ec4f4b5ad8c669f7e483',
    messagingSenderId: '3436283578',
    projectId: 'translation-app-a73ec',
    storageBucket: 'translation-app-a73ec.firebasestorage.app',
    iosClientId: '3436283578-a5essuvd6pmssana8450enprdktkctae.apps.googleusercontent.com',
    iosBundleId: 'com.hamaguchi.translationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcerile7xub_jHCLh70-WN__urs1ONM94',
    appId: '1:3436283578:ios:211c6bc0363c3bc7f7e483',
    messagingSenderId: '3436283578',
    projectId: 'translation-app-a73ec',
    storageBucket: 'translation-app-a73ec.firebasestorage.app',
    iosClientId: '3436283578-rek9h4a16qh53hh4jpk17tchpf395cab.apps.googleusercontent.com',
    iosBundleId: 'com.example.translationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvp4CGmegb2Vrm-gqUc9pGZPgZjh_DfmU',
    appId: '1:3436283578:web:430e929b4956be99f7e483',
    messagingSenderId: '3436283578',
    projectId: 'translation-app-a73ec',
    authDomain: 'translation-app-a73ec.firebaseapp.com',
    storageBucket: 'translation-app-a73ec.firebasestorage.app',
    measurementId: 'G-W0L5DMBY2X',
  );
}
